### ISSUE TITLE
3rd November 2022 - Morphir Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/morphir#115]
## Date

Thursday 3rd November 2022 - 11am ET / 3pm UK

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |

## Meeting notices

- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [ ] Convene, roll call, welcome new people (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [ ] Review Meeting Notices (see above)
- [ ] Approve previous meeting minutes - https://github.com/finos/morphir/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [ ] _Add Items Here_
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made

- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items

- [ ] Action 1
- [ ] Action 2
- [ ] ...

### WebEx info

**Webex:**
https://finos.webex.com/finos/j.php?MTID=mc06ba4f96e798bb141883a77db0aa4e5

**Dial-in**

- **US** +1-415-655-0003 US Toll
- **UK** +44-20319-88141 UK Toll
- **Meeting number:** 2555 504 4597

**Github Repo:** https://github.com/finos/morphir/

**Mailing List:** Email morphir+subscribe@finos.org to subscribe to our mailing list

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum @ Morgan Stanley

**Comment by AttilaMihaly** [comment]
Attila / MS

**Comment by RichardWagener365** [comment]
Richard/Codethink - Hi

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by eteridvalishvili** [comment]
Eteri / FINOS
