### ISSUE TITLE
1st December 2022 - Morphir Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/morphir#119]
## Date

Thursday 1st December 2022 - 11am ET / 4pm UK

## Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |

## Meeting notices

- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda

- [ ] Convene, roll call, welcome new people (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf)
- [ ] Review Meeting Notices (see above)
- [ ] Approve previous meeting minutes - https://github.com/finos/morphir/issues?q=is%3Aissue+is%3Aclosed+label%3Ameeting
- [ ] _Add Items Here_
- [ ] AOB, Q&A & Adjourn (5mins)

## Topics Raised

- **.NET support** - Peter raised interest in supporting F# as a backend language and tool.
- **Package Management** - The ability to depend on external projects is increasingly required.  It raises a number of challenges stemming from the fact that Morphir generates into other languages.  We need dependency management for Morphir that can work with the target platform standards.  Peter raised the option of generating the platform equivalent of lock files.  Attila proposed avoiding dependencies in the target languages by generating all dependencies with tree shaking for efficiency.
- **LCR** - Discussions around testing in open-source and how to get access to good test data.

## Action Items

- [ ] Connect on .NET for further planning.
- [ ] Write an issue for package management with a proposal in discussions.
- [ ] Raise testing and contribution in Open Reg Tech SIG.

### Zoom info

- https://zoom.us/j/95452540437?pwd=TEk0bitJcVFsK3lrWVZCYmxyTm5LZz09
- **Meeting ID:** 954 5254 0437
- **Passcode:** 778814

**Dial-in**

**Find your local number:** https://zoom.us/u/aFGSSGV9x

**Github Repo:** https://github.com/finos/morphir/

**Mailing List:** Email morphir+subscribe@finos.org to subscribe to our mailing list

**Comment by AttilaMihaly** [comment]
Hi

**Comment by psmulovics** [comment]
🙋‍♂️

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum @ Morgan Stanley

**Comment by RichardWagener365** [comment]
Hi
