### ISSUE TITLE
12th January 2023 - Morphir Project Meeting

### ISSUE THREAD

**Issue by mcleo-d** [finos/morphir#129]
# Date

Thursday 12th January 2023 - 11am ET / 4pm UK

# Untracked attendees

| Name | Firm | Comment |
| :--- | :--- | :------ |

# Meeting notices

- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies).

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

# Agenda

- [x] Project **morphir-scala** update
- [x] Functional / Relational mapping
- [x] Int64 (long) support
- [x] Package Management
- [x] Docker
- [x] IR structure

# Topics

## Scala support update
* Current focus is on execution in the JVM. Expected to be read in a few weeks.
* Authoring in Scala via Scala 3 macros expected to have progress in February.

## Functional / Relational Mapping
Given the upcoming work with Snowpark, it is a good opportunity to refactor the previous Spark work to be more generically built around supporting functional to relational mapping.  Alex proposed leveraging Quill for both defining the API and executing in the JVM.  This would be a natural fit with morphir-scala where the Morphir IR would be transpiled to Quill's Scala IR, which would make it available for SQL query generation.

## Package Management
Brief discussion on requirements, challenges, and ideas for dependency management across Morphir projects.  Suggested tools to explore were:
* SPDK
* WASM
* Maven

## Containerization
Suggestion for packaging the Morphir toolset, including Elm tools and supported libraries, as container image to enabled execution in restricted environments.  Visual Studio Code's ability to integrate with Docker images was mentioned.  There are other interesting opportunities to integrate with VS Code.  For example, by utilizing virtual workspaces and getting developers real-time feedback and decoration support natively in their code.

## IR structure
The issue was raised that it is challenging to work with the Morphir IR JSON structure because it is bespoke and doesn't conform to common languages' JSON bindings.  The request was to create a new version of the IR that does conform to common usage, specifically by using named fields.  Transition would be facilitated through bidirectional translation between the two.  This would allow tools written for either version to be interchangeable.  There are many trade-offs and supporting multiple versions would not be trivial.  It was decided to write a proposal that includes the cost and benefits for proper evaluation.

# Action Items

- [ ] Write a proposal for adding Int64 support to the IR (Capital One)
- [ ] Write a proposal / specification for the Decorations (Morgan Stanley)
- [ ] Acknowledge need for a proposal for Package Management when ready (Morgan Stanley)
- [ ] Proposal for IR structure changes to integrate better with common language JSON serialization (Capital One)
- [ ] Meeting with Quill and Snowflake to understand how functional to relational mapping can integrate with Snowflake tools.

### Zoom info

- https://zoom.us/j/95452540437?pwd=TEk0bitJcVFsK3lrWVZCYmxyTm5LZz09
- **Meeting ID:** 954 5254 0437
- **Passcode:** 778814

### Dial-in

- **Find your local number:** https://zoom.us/u/aFGSSGV9x

**Github Repo:** https://github.com/finos/morphir/

**Mailing List:** Email morphir+subscribe@finos.org to subscribe to our mailing list

**Comment by jgavronsky** [comment]
Jane @ FINOS here

**Comment by mcleo-d** [comment]
Hello 👋🏻

**Comment by DamianReeves** [comment]
Hello 👋🏾

**Comment by sfc-gh-sramsey** [comment]
Hello

**Comment by sfc-gh-dbryant** [comment]
Danny @ Snowflake -- Hello

**Comment by deusaquilus** [comment]
Hello

**Comment by deusaquilus** [comment]
(Alex Ioffe from Ziverge / Capital One, maintainer of [Quill](https://github.com/zio/zio-quill))

**Comment by DamianReeves** [comment]
Concerning packaging, have we looked at this: https://github.com/package-url/purl-spec

**Comment by stephengoldbaum** [comment]
Stephen Goldbaum @ Morgan Stanley
