### ISSUE TITLE
Many of the links in the readme are wrong

### ISSUE THREAD

**Issue by Strepto** [finos/morphir#28]
## Bug Report

Many of the links in the readme are dead or internal (goes to 404). This gives a bad impression of the maintenance of the repo and should be resolved :) 

### Steps to Reproduce:

![404](https://user-images.githubusercontent.com/3185998/91269488-82372d00-e777-11ea-8987-052056945854.gif)

### Expected Result:
Correct linking

### Actual Result:
404

### Environment:
GitHub.com

**Comment by AttilaMihaly** [comment]
Thanks for reporting. This was due to the recent move of our repos under the finos org. Hopefully it's all fixed now.
