### ISSUE TITLE
Stephen Goldbaum to be assigned to Morgan Stanley FINOS CCLA

### ISSUE THREAD

**Issue by mcleo-d** [finos/morphir#85]
## Description 

Stephen Goldbaum (@stephengoldbaum) should be assigned to the FINOS Morgan Stanley CCLA for pull request #84 to be successfully merged. The error being flagged in #84 is highlighted below. cc @bingenito

![Screenshot 2022-02-21 at 14 46 16](https://user-images.githubusercontent.com/6029572/154977709-387afa5d-9bcb-4a5a-8af4-86f908fa3336.png)

## Resolution

To resolve this error, @stephengoldbaum [please click here to be authorized](https://api.easycla.lfx.linuxfoundation.org/v2/repository-provider/github/sign/13399143/243284976/84/#/?version=2).

**Comment by bingenito** [comment]
Stephen has to change his Morgan Stanley organization membership to public and try again.

**Comment by bingenito** [comment]
@mcleo-d This should good now.

**Comment by mcleo-d** [comment]
Thank you @stephengoldbaum and @bingenito for resolving 👍🏻
